---
# defaults file for filetree_read

satellite_configuration_filetree_read_secure_logging: true

satellite_activation_keys: []
satellite_auth_sources_ldap: []
satellite_content_credentials: []
satellite_content_view_filters: []
satellite_content_views: []
satellite_content_view_versions: []
satellite_domains: []
satellite_host_collections: []
satellite_hostgroups: []
satellite_installation_mediums: []
satellite_job_templates: []
satellite_lifecycle_environments: []
satellite_locations: []
satellite_operatingsystems: []
satellite_organizations: []
satellite_partition_tables: []
satellite_products: []
satellite_provisioning_templates: []
satellite_repositories: []
satellite_repository_sets: []
satellite_roles: []
satellite_settings: []
satellite_subnets: []
satellite_sync_plans: []
satellite_users: []
satellite_usergroups: []
...
