---
- name: Ensure roles are correct
  redhat.satellite.role:
    # Mandatory parameters
    name: "{{ __current_role.name }}"
    # Optional parameters
    description: "{{ __current_role.description | default(omit) }}"
    organizations: "{{ __current_role.organizations | default(omit) }}"
    locations: "{{ __current_role.locations | default(omit) }}"
    filters: "{{ __current_role.filters | default(omit) }}"
    state: "{{ __current_role.state | default(omit) }}"
  loop: "{{ satellite_roles }}"
  loop_control:
    loop_var: __current_role
    label: "{{ __current_role.name }}"
  when:
    - satellite_roles is defined
    - __current_role.name not in (satellite_builtin_role_name_skips + satellite_builtin_role_name_skips_extra + (dispatch_roles_name_skips_extra | default([])))
    - (__current_role.builtin | default(0) | int) == 0
    - not (__current_role.locked | default(false) | bool)
  delegate_to: localhost
...
