---
- name: Ensure users are correct
  redhat.satellite.user:
    # Mandatory parameters
    login: "{{ __current_user.name }}"
    # Optional parameters
    firstname: "{{ __current_user.firstname | default(omit) }}"
    lastname: "{{ __current_user.lastname | default(omit) }}"
    mail: "{{ __current_user.mail | default(omit) }}"
    description: "{{ __current_user.description | default(omit) }}"
    admin: "{{ __current_user.admin | default(omit) }}"
    auth_source: "{{ __current_user.auth_source | default(omit) }}"
    default_organization: "{{ __current_user.default_organization | default(omit) }}"
    default_location: "{{ __current_user.default_location | default(omit) }}"
    organizations: "{{ __current_user.organizations | default(omit) }}"
    locations: "{{ __current_user.locations | default(omit) }}"
    roles: "{{ __current_user.roles | default(omit) }}"
    timezone: "{{ __current_user.timezone | default(omit) }}"
    locale: "{{ __current_user.locale | default(omit) }}"
    state: "{{ __current_user.state | default(omit) }}"
  loop: "{{ satellite_users }}"
  loop_control:
    loop_var: __current_user
    label: "{{ __current_user.name }}"
  when: satellite_users is defined
  delegate_to: localhost
...
