---
- name: Build unlocked provisioning templates for dispatch
  ansible.builtin.set_fact:
    __dispatch_provisioning_templates: >-
      {{
        satellite_provisioning_templates | default([])
        | rejectattr('locked', 'equalto', true)
        | list
      }}
  when: satellite_provisioning_templates is defined

- name: Create/Update Provisioning Templates
  redhat.satellite.provisioning_template:
    # Mandatory params
    name: "{{ __current_provisioning_template.name }}"
    template: "{{ __current_provisioning_template.template | infra.satellite_configuration.satellite_configuration_unwrap_raw_markers }}"
    # Optional params
    locked: "{{ __current_provisioning_template.locked | default(omit) }}"
    organizations: "{{ __current_provisioning_template.organizations | default(omit) }}"
    locations: "{{ __current_provisioning_template.locations | default(omit) }}"
    kind: "{{ __current_provisioning_template.kind | default(omit) }}"
    operatingsystems: "{{ __current_provisioning_template.operatingsystems | default(omit) }}"
    updated_name: "{{ __current_provisioning_template.updated_name | default(omit) }}"
    state: "{{ __current_provisioning_template.state | default('present') }}"
  loop: "{{ __dispatch_provisioning_templates | default([]) }}"
  loop_control:
    loop_var: __current_provisioning_template
    label: "{{ __current_provisioning_template.name }}"
  when: satellite_provisioning_templates is defined
  delegate_to: localhost

- name: Assign default Provisioning Templates to Operating Systems
  redhat.satellite.os_default_template:
    # Mandatory params
    operatingsystem: "{{ __current_provisioning_template[1] }}"
    template_kind: "{{ __current_provisioning_template[0].kind }}"
    # Optional params
    provisioning_template: "{{ __current_provisioning_template[0].name | default(omit) }}"
    state: "{{ __current_provisioning_template[0].state | default('present') }}"
  loop: "{{ __dispatch_provisioning_templates | default([]) | subelements('operatingsystems', skip_missing=true) }}"
  loop_control:
    loop_var: __current_provisioning_template
    label: "{{ __current_provisioning_template[0].name }}"
  when: satellite_provisioning_templates is defined
  delegate_to: localhost
...
