---
- name: Dispatch | Sanitize Auth Sources LDAP for Active Directory
  ansible.builtin.set_fact:
    __satellite_auth_sources_ldap_for_role: "{{ __satellite_auth_sources_ldap_for_role | default([]) + [__auth_source_entry] }}"
  loop: "{{ satellite_auth_sources_ldap | default([]) }}"
  loop_control:
    loop_var: __auth_source_item
    label: "{{ __auth_source_item.name | default(__auth_source_item.host) }}"
  vars:
    __auth_source_entry: >-
      {{
        (__auth_source_item | dict2items | rejectattr('key', 'equalto', 'use_netgroups') | items2dict)
        if (__auth_source_item.server_type | default('')) == 'active_directory'
        else __auth_source_item
      }}
  when: satellite_auth_sources_ldap | default([]) | length > 0
  no_log: "{{ satellite_configuration_dispatch_secure_logging }}"

- name: Dispatch | Prepare LDAP list for role import
  ansible.builtin.set_fact:
    _satellite_auth_sources_ldap_dispatch_list: "{{ __satellite_auth_sources_ldap_for_role }}"
  when:
    - satellite_auth_sources_ldap | default([]) | length > 0
    - __satellite_auth_sources_ldap_for_role is defined

- name: Dispatch | Apply Auth Sources LDAP
  ansible.builtin.include_role:
    name: redhat.satellite.auth_sources_ldap
  vars:
    satellite_username: "{{ satellite.admin.username }}"
    satellite_password: "{{ satellite.admin.password }}"
    satellite_server_url: "{{ satellite.server_url }}"
    satellite_validate_certs: "{{ satellite.validate_certs }}"
    satellite_auth_sources_ldap: "{{ _satellite_auth_sources_ldap_dispatch_list }}"
  when:
    - _satellite_auth_sources_ldap_dispatch_list is defined
    - _satellite_auth_sources_ldap_dispatch_list | length > 0
  no_log: "{{ satellite_configuration_dispatch_secure_logging }}"
...
