---
galaxy_info:
  author: ivarmu @ivarmu
  description: Reconcile live Satellite configuration against Configuration as Code
  company: Community
  license: GPL-2.0-or-later
  min_ansible_version: "2.16"

dependencies:
  - role: infra.satellite_configuration.global_vars

...
