---
- name: Installation Medium (Do Work) | Reset the results variable
  ansible.builtin.set_fact:
    result_api_response: {}

- name: Installation Medium (Do Work) | Get Installation Medium
  ansible.builtin.include_tasks: api_call.yaml
  vars:
    call_type: Installation Medium (Do Work)
    api_link: "/api/media/{{ __current_installation_medium.id }}/"

- name: Installation Medium (Do Work) | Block to do the job when there's a job to do
  when:
    - result_api_response.content is defined
    - result_api_response.content | length > 0
  block:
    - name: Installation Medium (Do Work) | Set Info List (can take a while...)
      ansible.builtin.set_fact:
        __rs_info_list: "{{ __rs_info_list + [result_api_response.content | from_json] }}"
...
