---
- name: Block
  tags:
    - 'organizations'
  block:
    - name: Get Organizations
      ansible.builtin.include_tasks: get_organizations.yaml

- name: Block
  tags:
    - 'locations'
  block:
    - name: Get Locations
      ansible.builtin.include_tasks: get_locations.yaml

- name: Block
  tags:
    - 'domains'
  block:
    - name: Get Domains
      ansible.builtin.include_tasks: get_domains.yaml

- name: Block
  tags:
    - 'subnets'
  block:
    - name: Get Subnets
      ansible.builtin.include_tasks: get_subnets.yaml

- name: Block
  tags:
    - 'repositories'
  block:
    - name: Get Repositories
      ansible.builtin.include_tasks: get_repositories.yaml

- name: Block
  tags:
    - 'repository_sets'
  block:
    - name: Get Repositories
      ansible.builtin.include_tasks: get_repository_sets.yaml

- name: Block
  tags:
    - 'hostgroups'
  block:
    - name: Get Host Groups
      ansible.builtin.include_tasks: get_hostgroups.yaml

- name: Block
  tags:
    - 'operatingsystems'
  block:
    - name: Get Operating Systems
      ansible.builtin.include_tasks: get_operatingsystems.yaml

- name: Block
  tags:
    - 'lifecycle_environments'
  block:
    - name: Get Lifecycle Environments
      ansible.builtin.include_tasks: get_lifecycle_environments.yaml

- name: Block
  tags:
    - 'content_views'
  block:
    - name: Get Content Views
      ansible.builtin.include_tasks: get_content_views.yaml

- name: Block
  tags:
    - 'products'
  block:
    - name: Get Custom Products
      ansible.builtin.include_tasks: get_products.yaml

- name: Block
  tags:
    - 'settings'
  block:
    - name: Get Settings
      ansible.builtin.include_tasks: get_settings.yaml

- name: Block
  tags:
    - 'content_credentials'
  block:
    - name: Get Content Credentials
      ansible.builtin.include_tasks: get_content_credentials.yaml

- name: Block
  tags:
    - 'activation_keys'
  block:
    - name: Get Activation Keys
      ansible.builtin.include_tasks: get_activation_keys.yaml

- name: Block
  tags:
    - 'sync_plans'
  block:
    - name: Get Sync Plans
      ansible.builtin.include_tasks: get_sync_plans.yaml

- name: Block
  tags:
    - 'auth_sources_ldap'
  block:
    - name: Get Auth Sources LDAP
      ansible.builtin.include_tasks: get_auth_sources_ldap.yaml

- name: Block
  tags:
    - 'host_collections'
  block:
    - name: Get Host Collections
      ansible.builtin.include_tasks: get_host_collections.yaml

- name: Block
  tags:
    - 'usergroups'
  block:
    - name: Get External Usergroups
      ansible.builtin.include_tasks: get_usergroups.yaml

- name: Block
  tags:
    - 'partition_tables'
  block:
    - name: Get Partition Tables
      ansible.builtin.include_tasks: get_partition_tables.yaml

- name: Block
  tags:
    - 'provisioning_templates'
  block:
    - name: Get Provisioning Templates
      ansible.builtin.include_tasks: get_provisioning_templates.yaml

- name: "Block to fix the output files' format"
  tags: always
  block:
    - name: "Search for all the generated files"
      ansible.builtin.find:
        paths: "{{ output_path }}"
        recurse: true
        patterns:
          - '*.yaml'
          - '*.yml'
      register: _generated_files

    - name: Gather system facts so we can find the user's home directory
      ansible.builtin.setup:
        gather_subset:
          - min

    - name: "Create a secure temporary directory in the user's home"
      ansible.builtin.tempfile:
        state: directory
        path: "{{ ansible_user_dir }}"
        prefix: my_binary_run_
      register: temp_exec_dir

    - name: "Copy the 'yq' binary to be able to execute it"
      ansible.builtin.copy:
        src: yq_v4.52.4
        dest: "{{ temp_exec_dir.path }}/yq"
        mode: '0755'

    - name: "Re-write all the generated files to make them more readable (Content Credentials special case)"
      ansible.builtin.shell: |
        {{ temp_exec_dir.path }}/yq -i '(.satellite_content_credentials[].content) |= (trim + "\n") | (.satellite_content_credentials[].content) style="literal"' '{{ _current_file.path }}';
        {{ temp_exec_dir.path }}/yq -i -P '{{ _current_file.path }}'
      when: "'content_credentials' in _current_file.path"
      changed_when: true
      loop: "{{ _generated_files.files }}"
      loop_control:
        loop_var: _current_file
        label: "{{ _current_file.path }}"
      # noqa: risky-shell-pipe
      # ^ The shell command above does't use any pipe (only in the yq search)

    - name: "Re-write all the generated files to make them more readable"
      ansible.builtin.shell: "{{ temp_exec_dir.path }}/yq -i -P '{{ _current_file.path }}' && echo '...' >> '{{ _current_file.path }}'"
      changed_when: true
      loop: "{{ _generated_files.files }}"
      loop_control:
        loop_var: _current_file
        label: "{{ _current_file.path }}"
  always:
    - name: Clean up the temporary directory
      ansible.builtin.file:
        path: "{{ temp_exec_dir.path }}"
        state: absent
...
