---
- name: Export Satellite Configuration
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.satellite_configuration
  tasks:
    - name: Resolve source Satellite connection for export
      ansible.builtin.set_fact:
        satellite: "{{ satellite_source }}"
      when: satellite_source is defined

    - name: Ensure that the output_path exists
      ansible.builtin.file:
        path: "{{ output_path }}"
        mode: "0777"
        state: directory
      tags: always

    - name: Get Satellite Objects
      ansible.builtin.import_role:
        name: infra.satellite_configuration.filetree_create
...
