---
- name: Playbook to test filetree_read and dispatch roles
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - infra.satellite_configuration
    - redhat.satellite
  vars:
    satellite_configuration_filetree_path: configs
  module_defaults:
    group/redhat.satellite.satellite:
      username: "{{ satellite.admin.username }}"
      password: "{{ satellite.admin.password }}"
      server_url: "{{ satellite.server_url }}"
      validate_certs: "{{ satellite.validate_certs }}"
  tasks:
    - name: Resolve target Satellite connection for import
      ansible.builtin.set_fact:
        satellite: "{{ satellite_target }}"
      when: satellite_target is defined

    - name: Load Satellite configuration from filetree
      ansible.builtin.import_role:
        name: infra.satellite_configuration.filetree_read

    - name: Apply Satellite configuration
      ansible.builtin.import_role:
        name: infra.satellite_configuration.dispatch
...
